### PR TITLE
Removing existing requirement of finalizer length > 0

### PR DESCRIPTION
**Pull request by naemono**
ensuring required items are actually required according to sensu documentation
adding openapi-gen generated validation
locking in json-iterator to same version as k8s version
ensuring that in each informer, that the finalizer is added, only if it's not already being deleted

### CODE REVIEW

**Comment by jonsabo** [comment]
>adding openapi-gen generated validation
can you add docs on how to re-generate these in the future if we make changes?

**Comment by jonsabo** [comment]
I'm also kind of wary of going down the crdutil path further since if I understand correctly, it only works if we have the operator create the CRD (rather than moving it to helm). Which right now we do, but I think most of our other projects ended up removing crdutil and just having helm deploy CRDs to make it easier to work with updates and new CRD features. So I'm not sure we want to entrench that further if we might change it soon. This might be totally off base though, curious of your thoughts

**Comment by jonsabo** [comment]
Other than that the underscore to camelCase and omitemptys looked helpful, and the finalizer stuff should be good. One thing this got me thinking about was we might want to start emitting events sooner than later to make troubleshooting a little bit easier.

**Comment by naemono** [comment]
> > adding openapi-gen generated validation
> 
> can you add docs on how to re-generate these in the future if we make changes?

Good point, yes I will now

**Pull request merged**
